#!/bin/bash

#variables


  sourcedir=$sourcedir
  destdir=$destdir
  cpuser=$cpuser
  cpserver=$cpserver



  # Welcher
  echo -e "Welche Ordner soll kopiert werden?"
  read -r sourcedir
  # Wohin
  echo -e "Wohin soll der Ordner kopiert werden?"
  read -r destdir

  rsync -avzh --progress --dry-run suv@tiffy:$sourcedir $destdir
